services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.12.1
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped
    pid: host
    ports:
      - '9100:9100'
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/host:ro'
    networks:
      - monitoring_net

  prometheus:
    image: prom/prometheus:v3.14.0
    container_name: prometheus
    ports:
      - '9090:9090'
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/targets.yml:/etc/prometheus/targets.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana:13.2.2
    container_name: grafana
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring_net

  pve-exporter:
    image: prompve/prometheus-pve-exporter:3.9.0
    container_name: pve-exporter
    ports:
      - '9221:9221'
    restart: unless-stopped
    volumes:
      - ./secrets/pve.yml:/etc/prometheus/pve.yml:ro
    networks:
      - monitoring_net

  pve-qga-exporter:
    build:
      context: ./qga-exporter
    image: local/pve-qga-exporter:1.0.0
    container_name: pve-qga-exporter
    restart: unless-stopped
    volumes:
      - ./secrets/pve.yml:/etc/prometheus/pve.yml:ro
      - ./prometheus/targets.yml:/etc/prometheus/targets.yml:ro
    expose:
      - '9222'
    networks:
      - monitoring_net

volumes:
  prometheus-data: {}
  grafana-data: {}

networks:
  monitoring_net:
    driver: bridge
